### ISSUE TITLE
possible to control the maximum size of each sst file?

### ISSUE THREAD

**Issue by superdolt** [bytedance/terarkdb#106]
1. possible to control the maximum size of each sst file?
2. i cant seem to verify if terark-zip is working with sst_dump. how do i check if it's working?

**Comment by skyzh** [comment]
Maximum seems not controllable. Typically, we set `target_file_size_base` for expected SST size and `target_blob_file_size` for expected blob file size.

For the second question, it is duplicated with https://github.com/bytedance/terarkdb/issues/101
