### ISSUE TITLE
Patricia Trie memtable doesn't work well on multi-threading workloads

### ISSUE THREAD

**Issue by royguo** [bytedance/terarkdb#12]
[BUG]:
### Expected behavior
`db_bench` readrandomwriterandom works well on multi-threading workloads and get better performacne (ops and latency) than skiplist memtable

### Actual behavior
Use `db_bench` for multi-threading (more than 2 threads) reading and writing, background write hangs there without any useful log.

### Steps to reproduce the behavior
`db_bench` --memtablerep=skip_list ....

**Comment by royguo** [comment]
Looks like a bug in terark-zip, refer to this issues: https://github.com/bytedance/terark-zip/pull/1

**Comment by mm304321141** [comment]
Fixed #29
