### ISSUE TITLE
How to build and install TerarkDB with ZenFS enabled?

### ISSUE THREAD

**Issue by lovers-under-moon** [bytedance/terarkdb#149]
The readme(https://github.com/bzbd/zenfs/blob/dev/README.md) is for build and install RocksDB with ZenFS enabled.

**Comment by skyzh** [comment]
Running `build.sh` on https://github.com/bytedance/terarkdb/tree/zenfs-dev-1.4 should by default enable ZenFS.

**Comment by lovers-under-moon** [comment]
Thanks!

**Comment by skyzh** [comment]
> Running `build.sh` on https://github.com/bytedance/terarkdb/tree/zenfs-dev-1.4 should by default enable ZenFS.

zenfs branch has already been merged to dev1.4. Consider using dev1.4 and set `WITH_ZENFS` to `ON` in CMake.
