### ISSUE TITLE
Can not clone terarkdb/third-party/metrics2-cmake when I run build.sh

### ISSUE THREAD

**Issue by lovers-under-moon** [bytedance/terarkdb#150]
![image](https://user-images.githubusercontent.com/45291298/141953636-d097d0ba-42fd-426c-8876-29daac753b0e.png)
My branch is zenfs-dev-1.4.

**Comment by skyzh** [comment]
Yes, that's a ByteDance's internal dependency that didn't get removed. It's a bug on `dev-zenfs` branch.

By the way, it seems that TerarkDB4ZNS support has already being merged to dev1.4. Consider using `dev1.4` and set CMake property `WITH_ZENFS` to `ON`.

**Comment by lovers-under-moon** [comment]
There is another error when I run build.sh.

![image](https://user-images.githubusercontent.com/45291298/141975256-8423267b-3369-4e76-b135-880d70867ef0.png)

Now my branch is dev1.4 and CMake property WITH_ZENFS=ON, WITH_BYTEDANCE_METRICS=OFF.

![image](https://user-images.githubusercontent.com/45291298/141975391-9df1b06d-3c67-4d97-9d27-29bceb700bc9.png)
![image](https://user-images.githubusercontent.com/45291298/141975509-1d068656-dc6d-425b-a3b8-50567aef3230.png)

**Comment by skyzh** [comment]
Did you re-run cmake config (or remove the cmake's build folder?) It seems that everything works perfectly on my machine.

**Comment by lovers-under-moon** [comment]
After deleting the output folder,it runs well.
Thanks!

**Comment by lovers-under-moon** [comment]
![IMG_20211116_211422](https://user-images.githubusercontent.com/45291298/141992017-28028a30-0521-4477-ba94-f7f682ce86d9.jpg)
When I build the zenfs utility,another error occurred.It seems files of zenfs are incomplete?
![@MD3RHIC81R}RQEPQ7L_K82(1)](https://user-images.githubusercontent.com/45291298/141992064-c41247c6-4a82-4130-ad04-751b5d92b537.png)

**Comment by skyzh** [comment]
ZenFS utility is automatically built with TerarkDB. See the output folder and you will find `zenfs`. No need to `make` it again.
