### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by superdolt** [bytedance/terarkdb#162]
how do i resolve with build.sh?

[ 92%] Built target terarkdb
make[2]: *** No rule to make target 'lib/libjemalloc.a', needed by 'hash_table_bench'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:381: CMakeFiles/hash_table_bench.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target 'lib/libjemalloc.a', needed by 'cache_bench'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:459: CMakeFiles/cache_bench.dir/all] Error 2
make[2]: *** No rule to make target 'lib/libjemalloc.a', needed by 'memtablerep_bench'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:499: CMakeFiles/memtablerep_bench.dir/all] Error 2
make[2]: *** No rule to make target 'lib/libjemalloc.a', needed by 'column_aware_encoding_exp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:341: CMakeFiles/column_aware_encoding_exp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by skyzh** [comment]
Did you clone all submodules? By the way, would you please clean build data, rebuild, and paste full log?

**Comment by yapple** [comment]
Normally, build.sh will init submodule. 
Maybe you can try to close WITH JEMALLOC in CMAKE
`cd output && cmake .. -DWITH_JEMALLOC=OFF && make -j`
