### ISSUE TITLE
Please set default  branch to a compilable one

### ISSUE THREAD

**Issue by orca-zhang** [bytedance/terarkdb#163]
`dev 1.4` branch now cannot be compiled successfully under MacOS, but `master` is OK.

**Comment by skyzh** [comment]
What's the error message?

**Comment by skyzh** [comment]
And this sounds like the same issue as #26. Please don't file duplicated issues unless you find some extra things.

**Comment by orca-zhang** [comment]
The `CMakeLists.txt` of `dev.1.4` is very different from the `master`'s.

I've tried to fix them under `dev.1.4`, but too many, and I gave up.

e.g.:
> cp: illegal option -- T
> usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
>       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

CMakeLists.txt
> CONFIGURE_COMMAND cp -rT ${CMAKE_CURRENT_SOURCE_DIR}/jemalloc . && bash autogen.sh && "CFLAGS=-fPIC" "CXXFLAGS=-fPIC" "LDFLAGS=-fPIC" ./configure --prefix=${CMAKE_BINARY_DIR} --enable-prof

I tried to change `cp -rT` to `cp -r` will occur `autogen.sh` not found error coz that directory not changed.

And `JEMALLOC_NO_RENAME` related errors that symbols not match and etc.

I even want to downgrade to choose traditional `RocksDB` before I checkout `master` branch and luckily passed the compilation easily.

**Comment by skyzh** [comment]
We only maintain dev1.4 branch.

**Comment by orca-zhang** [comment]
> 

So that's the problem, errors only occurred under `dev.1.4` you still maintained, and `master` is OK.

**Comment by skyzh** [comment]
> So that's the problem, errors only occurred under dev.1.4 you still maintained, and master is OK.

It doesn't matter what branch can compile or what branch can't -- dev.1.4 is the only official one that is actively maintained.

> Please set default branch to a compilable one

The issue title is also misleading. We should fix the compile issue, instead of simply switching to a previous version.

**Comment by orca-zhang** [comment]
You may misunderstand what I said, that in my opinion, the default branch should be a stable branch which can be easily launched as a quick start. Not about is or not under maintained. Will you long time R&D under `dev.1.4` that will not be merged to `master`, or it is just a dev branch?
In the tutorial, it is not mentioned that new visitors should change the branch to `master`. So I regard the current default branch `dev.1.4` as the stable one by convention, although it is weird. And this issue is just my subjective advise to you, change or not, both are OK, and it is just up to you.
It is a pity that we gain loss if them can't compile this awesome project.

**Comment by orca-zhang** [comment]
@rockeet

**Comment by yapple** [comment]
Unfortunately, Some new features broke the compilation under MacOS, we will fix it. Thank you so much for your feedback.

**Comment by yapple** [comment]
If you want to use TerarkDB to do some performance optimization, such as write amplification, performance stability optimization or others, we are very interested in your scenario

**Comment by skyzh** [comment]
> Will you long time R&D under dev.1.4 that will not be merged to master, or it is just a dev branch?

If I understand our roadmap correctly, it won't be merged to master.

> the default branch should be a stable branch which can be easily launched as a quick start

macOS is not our tier-1 support. TerarkDB can be easily compiled on distros such as Ubuntu. As you can see in the [commit history](https://github.com/bytedance/terarkdb/commits/dev.1.4), every commit can be compiled on CI. Furthermore, some advanced feature such as ZNS support isn't possible on macOS.

> It is a pity that we gain loss if them can't compile this awesome project.

Sorry for you bad experience. But I have to say we have a long way to go before gaining macOS support. And even if we support macOS, some core features might be disabled.

**Comment by skyzh** [comment]
> the default branch should be a stable branch which can be easily launched as a quick start

The "stability guarantee" doesn't seem to be a convention. Most of the open-source projects use master as the develop branch. They merge new features to it and the features might be reverted at any time. Only "releases" are considered stable.

**Comment by orca-zhang** [comment]
I think you're right, new features broke the compilation(that no CI covered) under unsupported MacOS. That's great, it will really do me a favor if you're considering to support MacOS. 👍

**Comment by skyzh** [comment]
> I think you're right, new features broke the CI under unsupported MacOS. That's great, it will really do me a favor if you're considering to support MacOS. 👍

Thanks for filing this issue anyway. We will track macOS related changes in the original one https://github.com/bytedance/terarkdb/issues/26. Feel free to subscribe to it. (and maybe leave more comments)
