### ISSUE TITLE
The link of slack channel is invalid

### ISSUE THREAD

**Issue by liukun4515** [bytedance/terarkdb#171]

**Comment by royguo** [comment]
I can visit the slack channel without problem, could provide a screenshot or more error message?

@liukun4515

**Comment by royguo** [comment]
@liukun4515 thanks, the old link was expired, please use the latest one: https://join.slack.com/t/terarkdb/shared_invite/zt-zxo71hwl-j_K4OIQ~p5_SsT4RrFesxg

This link will never expire.

**Comment by liukun4515** [comment]
> 

thanks, now it works.
