### ISSUE TITLE
when to use `TerarkDB` instead of `RocksDB`

### ISSUE THREAD

**Issue by orca-zhang** [bytedance/terarkdb#177]
I‘ve created a continuous benchmark repo to compare the performance between `TerarkDB` and `RocksDB`.

both of them with JEMALLOC on and all the compression extensions

https://github.com/benchplus/terarkdb

commit f1b51f1 use terark-zip table as tutorial said
and former cases without terark-zip

https://benchplus.github.io/terarkdb/dev/bench/

In a result of this simple comparison, only in `GetAll`case(that iterate all the items),the result of `TerarkDB` is better than `RocksDB`'s. Others are roughly the same I think.

So, the difference comes from the scale of the data, or the hardware(NVMe SSD), or the params has not been optimized, or the golang wrapper?

**Comment by yapple** [comment]
Your bench looks wonderful,  you need to add blob_size operation in your gorocksdb in order to open the  KV separation feature in terarkdb.

**Comment by yapple** [comment]
I  list the params in C++ like that
`  options.blob_size = 1024;`

**Comment by orca-zhang** [comment]
Thanks a ton. I'll have a try. : )

**Comment by yapple** [comment]
in options.go add a function to call C.rocksdb_options_set_blob_size

**Comment by yapple** [comment]
![image](https://user-images.githubusercontent.com/10256548/146889580-d2835704-2366-4481-8034-229f5d3487a0.png)

I have run the bench you supplied, it finished in 18.778s. The bench is too short to show the IO performance improvement of terarkdb.
