### ISSUE TITLE
Some source code use std::move a const reference object, it mostly returns a copy of the object

### ISSUE THREAD

**Issue by sniper00** [bytedance/terarkdb#20]
> Note: Please label your issues type before submit, e.g. [Enhancement], [docs], [bug] etc.

[BUG]:
### Steps to reproduce the behavior

[Enhancement]:
### Problem
When called on a const object, std::move returns a copy of the object, which is likely not the developer's intent.
https://docs.microsoft.com/en-us/cpp/code-quality/c26478?view=msvc-160

https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/db/compaction.h#L61
### Solution
If you don't have any solution, leave this section empty

**Comment by royguo** [comment]
@levisonchen Please help to verify if `RangeStorage` is suitable to add a `const T&&` constructor to avoid data copying.

**Comment by mm304321141** [comment]
thx for pointing out the issue ~
