### ISSUE TITLE
[BUG] CMake inconsistencies

### ISSUE THREAD

**Issue by noobpwnftw** [bytedance/terarkdb#21]
[BUG]:
### Expected behavior
1. All dependency libraries are placed in `output/lib` folder
2. Build commands honor parallelism settings
3. Portable compiles are actually portable
4. Commonly used build targets are production-ready

### Actual behavior
1. Snappy library is placed under `output/lib64` folder
2. Dependency libraries have inconsistent `-j` commands
3. `PORTABLE=1` does not cover terark-zip library
4. `RelWithDebInfo` is actually `-DDEBUG`, ASAN is default ON

### Steps to reproduce the behavior
1. `./build.sh`
2. 
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/third-party/CMakeLists.txt#L32
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/third-party/CMakeLists.txt#L52
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/third-party/CMakeLists.txt#L155
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/third-party/CMakeLists.txt#L175
3. https://github.com/bytedance/terark-zip/blob/c55ddd7f8ee9b7f71f3ac0f681d44aaf73f1c7af/CMakeLists.txt#L19
4. 
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/CMakeLists.txt#L17-L18
https://github.com/bytedance/terarkdb/blob/668b7e5e83bdce27f863da59a13e2baacde48399/CMakeLists.txt#L48

**Comment by royguo** [comment]
@noobpwnftw Thanks for your report, we will investigate more into it and fix it soon

**Comment by royguo** [comment]
Hi, @noobpwnftw, I've checked your issuses:

1. Snappy library is placed under output/lib64 folder
2. Dependency libraries have inconsistent -j commands

Will try to re-produce and fix it.


3. PORTABLE=1 does not cover terark-zip library
terark-zip was not designed for portable devices neither tested under portable devices, we will cover it in the future.

4. RelWithDebInfo is actually -DDEBUG, ASAN is default ON
The `RelWithDebInfo` doesn't has a `-DDEBUG` flag so we cannot build `db_bench` or other tools under this build type. Adding a -DDEBUG flag will not hurt too much performance but helps us debugging (for production environment we recommend to use Release build type)

**Comment by noobpwnftw** [comment]
Thanks.

For 3, common understanding of "portable" is that the compiled binary is machine independent, in which case, when compiling with `PORTABLE=1`(the main project will not have `-march=native`), these intrinsic functions(https://github.com/bytedance/terark-zip/blob/c55ddd7f8ee9b7f71f3ac0f681d44aaf73f1c7af/src/terark/util/atomic.hpp#L47-L65) can fail at link time.

For 4, you can build tools without `-DDEBUG`, but not tests, not sure if that is what you mean, as for debugging, with asserts on, this gets triggered quite often:
https://github.com/bytedance/terark-zip/blob/c55ddd7f8ee9b7f71f3ac0f681d44aaf73f1c7af/src/terark/fsa/cspptrie.cpp#L2647

**Comment by royguo** [comment]
Sounds reasonable, will check.

Also if you can push a PR, it will be great :)

**Comment by noobpwnftw** [comment]
@royguo #23

**Comment by royguo** [comment]
Merged! Thanks
