### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by shnuhw** [bytedance/terarkdb#213]
安装的时候遇到了这个问题，如何解决， 谢谢：
creating pkgconfig
Installing libraries
Installing headers in /terarkdb/build/include
lz4 libraries installed
Installing binaries
Installing man pages
lz4 installation completed
[ 12%] Completed 'lz4-project'
[ 12%] Built target lz4-project
[100%] Linking CXX static library libsnappy.a
[100%] Built target snappy
[ 13%] Performing install step for 'snappy-project'
Consolidate compiler generated dependencies of target snappy
[100%] Built target snappy
Install the project...
-- Install configuration: "Release"
-- Installing: /terarkdb/build/lib/libsnappy.a
-- Installing: /terarkdb/build/include/snappy-c.h
-- Installing: /terarkdb/build/include/snappy-sinksource.h
-- Installing: /terarkdb/build/include/snappy.h
-- Installing: /terarkdb/build/include/snappy-stubs-public.h
-- Installing: /terarkdb/build/lib/cmake/Snappy/SnappyTargets.cmake
-- Installing: /terarkdb/build/lib/cmake/Snappy/SnappyTargets-release.cmake
-- Installing: /terarkdb/build/lib/cmake/Snappy/SnappyConfig.cmake
-- Installing: /terarkdb/build/lib/cmake/Snappy/SnappyConfigVersion.cmake
[ 13%] Completed 'snappy-project'
[ 13%] Built target snappy-project
[ 87%] Linking CXX static library lib/libgflags.a
[100%] Linking CXX static library lib/libgflags_nothreads.a
[100%] Built target gflags_static
[100%] Built target gflags_nothreads_static
[ 13%] Performing install step for 'gflags-project'
Consolidate compiler generated dependencies of target gflags_static
Consolidate compiler generated dependencies of target gflags_nothreads_static
[ 50%] Built target gflags_nothreads_static
[100%] Built target gflags_static
Install the project...
-- Install configuration: "Release"
-- Installing: /terarkdb/build/lib/libgflags.a
-- Installing: /terarkdb/build/lib/libgflags_nothreads.a
-- Installing: /terarkdb/build/include/gflags/gflags.h
-- Installing: /terarkdb/build/include/gflags/gflags_declare.h
-- Installing: /terarkdb/build/include/gflags/gflags_completions.h
-- Installing: /terarkdb/build/include/gflags/gflags_gflags.h
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-config.cmake
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-config-version.cmake
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-targets.cmake
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-targets-release.cmake
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-nonamespace-targets.cmake
-- Installing: /terarkdb/build/lib/cmake/gflags/gflags-nonamespace-targets-release.cmake
-- Installing: /terarkdb/build/bin/gflags_completions.sh
-- Installing: /terarkdb/build/lib/pkgconfig/gflags.pc
-- Installing: /root/.cmake/packages/gflags/18764eab45a3e5e757c88aa87f9318ae
[ 14%] Completed 'gflags-project'
[ 14%] Built target gflags-project
creating versioned links
[ 15%] Performing install step for 'zstd-project'
Installing libraries
Installing includes
zstd static and shared library installed
==> building zstd with .gz decompression support
Installing binaries
Installing man pages
zstd installation completed
[ 15%] Completed 'zstd-project'
[ 15%] Built target zstd-project
make: *** [all] Error 2

**Comment by yapple** [comment]
在 build 目录下 make -j1 打印下输出吧

**Comment by shnuhw** [comment]
> 

gcc版本过低导致的，但是我升级了gcc版本之后jemalloc出现了问题，还是报错

 16%] Performing build step for 'jemalloc-project'
cp include/jemalloc/internal/private_namespace.gen.h include/jemalloc/internal/private_namespace.gen.h
[ 16%] Performing install step for 'jemalloc-project'
/usr/bin/install -c -m 644 include/jemalloc/jemalloc.h /terarkdb/build/include/jemalloc
/usr/bin/install -c -m 755 bin/jemalloc-config /terarkdb/build/bin
/usr/bin/install -c -m 755 lib/libjemalloc.a /terarkdb/build/lib
/usr/bin/install -c -m 644 jemalloc.pc /terarkdb/build/lib/pkgconfig
/usr/bin/install -c -m 755 bin/jemalloc.sh /terarkdb/build/bin
Missing xsltproc.  doc/jemalloc.html not (re)built.
/usr/bin/install -c -m 644 doc/jemalloc.html /terarkdb/build/share/doc/jemalloc
Missing xsltproc.  doc/jemalloc.3 not (re)built.
/usr/bin/install -c -m 644 doc/jemalloc.3 /terarkdb/build/share/man/man3
/usr/bin/install -c -m 755 bin/jeprof /terarkdb/build/bin
/usr/bin/install -c -m 755 lib/libjemalloc_pic.a /terarkdb/build/lib
[ 16%] Completed 'jemalloc-project'
[ 16%] Built target jemalloc-project
make: *** [all] Error 2
[root@c4f291021ef2 terarkdb]# cd build
[root@c4f291021ef2 build]# ls
CMakeCache.txt  Makefile             RocksDBConfigVersion.cmake  cmake_install.cmake  lib  share         third-party
CMakeFiles      RocksDBConfig.cmake  bin                         include              man  terark-tools  tools
[root@c4f291021ef2 build]# make -j1
[  0%] Building CXX object CMakeFiles/rocksdb_build_version.dir/util/build_version.cc.o
c++: error: unrecognized command line option '-std=c++14'
make[2]: *** [CMakeFiles/rocksdb_build_version.dir/util/build_version.cc.o] Error 1
make[1]: *** [CMakeFiles/rocksdb_build_version.dir/all] Error 2
make: *** [all] Error 2
[root@c4f291021ef2 build]#
[root@c4f291021ef2 build]# gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by yapple** [comment]
cd build && cmake .. -DWITH_JEMALLOC=OFF && make -j8

**Comment by shnuhw** [comment]
> cd build && cmake .. -DWITH_JEMALLOC=OFF && make -j8

[root@c4f291021ef2 build]# cmake .. -DWITH_JEMALLOC=OFF && make -j8
[terarkdb] cmake install prefix: /terarkdb/build/build
-- terarkdb namespace: terarkdb
[terarkdb] FORCE_RELEASE_BUILD = OFF, cmake_build_type = RelWithDebInfo
[terarkdb] TERARKDB_NAMESPACE=terarkdb
[terarkdb] WITH_TOOLS = ON, WITH_ASAN = OFF, WITH_TESTS = OFF
[terarkdb] WITH_JEMALLOC = OFF, WITH_COVERAGE=OFF
[terarkdb] CMAKE_BUILD_TYPE=RelWithDebInfo, BUILD_SUFFIX=r
[terarkdb] CMAKE_CXX_FLAGS=
[terarkdb] CMAKE_THREAD_LIBS_INIT=-lpthread
[terarkdb] BYTEDANCE_METRICS_PATH=
[terarkdb/third-party] gtest target not exist, let's build it!
[terarkdb/third-party] snappy target not exist, let's build it!
[terarkdb/third-party] zlib target not exist, let's build it!
[terarkdb/third-party] gflags target not exist, let's build it!
[terarkdb/third-party] zstd target not exist, let's build it!
[terarkdb/third-party] lz4 target not exist, let's build it!
[terarkdb/third-party] bzip2 target not exist, let's build it!
[terarkdb] gflags include dir: /terarkdb/build/include
[terarkdb] without boost
[terarkdb] gtest include dir: /terarkdb/third-party/gtest-1.8.1/fused-src/gtest/..
[terarkdb] snappy include dir: /terarkdb/build/include
[terarkdb] zlib include dir: /terarkdb/build/include
[terarkdb] bzip2 include dir : /terarkdb/build/include
[terarkdb] lz4 include dir : /terarkdb/build/include
[terarkdb] zstd include dir : /terarkdb/build/include
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
-- Enabling RTTI
-- JNI library is disabled
[terark-tools] Build batch_write_bench...
-- Configuring done
-- Generating done
-- Build files have been written to: /terarkdb/build
[  2%] Built target gflags-project
[  3%] Building CXX object CMakeFiles/rocksdb_build_version.dir/util/build_version.cc.o
[  6%] Built target zstd-project
[  8%] Built target zlib-project
[  8%] Building CXX object CMakeFiles/testharness.dir/util/testharness.cc.o
[ 10%] Built target lz4-project
[ 13%] Built target bzip2-project
c++: error: unrecognized command line option '-std=c++14'
make[2]: *** [CMakeFiles/rocksdb_build_version.dir/util/build_version.cc.o] Error 1
make[1]: [ 15%] Built target snappy-project
*** [CMakeFiles/rocksdb_build_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
c++: error: unrecognized command line option '-std=c++14'
make[2]: *** [CMakeFiles/testharness.dir/util/testharness.cc.o] Error 1
make[1]: *** [CMakeFiles/testharness.dir/all] Error 2
[ 15%] Building CXX object third-party/gtest-1.8.1/fused-src/gtest/CMakeFiles/gtest.dir/gtest-all.cc.o
c++: error: unrecognized command line option '-std=c++14'
make[2]: *** [third-party/gtest-1.8.1/fused-src/gtest/CMakeFiles/gtest.dir/gtest-all.cc.o] Error 1
make[1]: *** [third-party/gtest-1.8.1/fused-src/gtest/CMa

**Comment by shnuhw** [comment]
> cd build && cmake .. -DWITH_JEMALLOC=OFF && make -j8

好像是c++版本问题，我升级下看看

**Comment by shnuhw** [comment]
> cd build && cmake .. -DWITH_JEMALLOC=OFF && make -j8

我升级了c++，出现了新的问题：
[ 90%] Building CXX object tools/CMakeFiles/db_repl_stress.dir/db_repl_stress.cc.o
[ 90%] Building CXX object CMakeFiles/range_del_aggregator_bench.dir/db/range_del_aggregator_bench.cc.o
[ 90%] Building CXX object terark-tools/batch-write-bench/CMakeFiles/batch_write_bench.dir/batch_write_bench.cc.o
[ 92%] Building CXX object tools/CMakeFiles/sst_dump.dir/sst_dump.cc.o
[ 91%] Building CXX object tools/CMakeFiles/rocksdb_dump.dir/dump/rocksdb_dump.cc.o
[ 92%] Building CXX object tools/CMakeFiles/db_sanity_test.dir/db_sanity_test.cc.o
[ 92%] Building CXX object CMakeFiles/hash_table_bench.dir/utilities/persistent_cache/hash_table_bench.cc.o
[ 93%] Building CXX object tools/CMakeFiles/ldb.dir/ldb.cc.o
[ 94%] Building CXX object tools/CMakeFiles/rocksdb_undump.dir/dump/rocksdb_undump.cc.o
[ 94%] Linking CXX executable sst_dump
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/sst_dump] Error 1
make[1]: *** [tools/CMakeFiles/sst_dump.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX executable hash_table_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [hash_table_bench] Error 1
make[1]: *** [CMakeFiles/hash_table_bench.dir/all] Error 2
[ 94%] Linking CXX executable ldb
[ 94%] Linking CXX executable cache_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/ldb] Error 1
make[1]: *** [tools/CMakeFiles/ldb.dir/all] Error 2
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [cache_bench] Error 1
make[1]: *** [CMakeFiles/cache_bench.dir/all] Error 2
[ 94%] Linking CXX executable rocksdb_dump
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/rocksdb_dump] Error 1
make[1]: *** [tools/CMakeFiles/rocksdb_dump.dir/all] Error 2
[ 94%] Linking CXX executable rocksdb_undump
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/rocksdb_undump] Error 1
make[1]: *** [tools/CMakeFiles/rocksdb_undump.dir/all] Error 2
[ 95%] Linking CXX executable write_stress
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/write_stress] Error 1
make[1]: *** [tools/CMakeFiles/write_stress.dir/all] Error 2
[ 96%] Linking CXX executable column_aware_encoding_exp
[ 96%] Linking CXX executable batch_write_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [column_aware_encoding_exp] Error 1
make[1]: *** [CMakeFiles/column_aware_encoding_exp.dir/all] Error 2
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [terark-tools/batch-write-bench/batch_write_bench] Error 1
make[1]: *** [terark-tools/batch-write-bench/CMakeFiles/batch_write_bench.dir/all] Error 2
[ 96%] Linking CXX executable db_repl_stress
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/db_repl_stress] Error 1
make[1]: *** [tools/CMakeFiles/db_repl_stress.dir/all] Error 2
[ 97%] Linking CXX executable db_sanity_test
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/db_sanity_test] Error 1
make[1]: *** [tools/CMakeFiles/db_sanity_test.dir/all] Error 2
[ 98%] Linking CXX executable range_del_aggregator_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [range_del_aggregator_bench] Error 1
make[1]: *** [CMakeFiles/range_del_aggregator_bench.dir/all] Error 2
[ 98%] Linking CXX executable memtablerep_bench
[ 99%] Linking CXX executable table_reader_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [memtablerep_bench] Error 1
make[1]: *** [CMakeFiles/memtablerep_bench.dir/all] Error 2
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [table_reader_bench] Error 1
make[1]: *** [CMakeFiles/table_reader_bench.dir/all] Error 2
[ 99%] Linking CXX executable db_stress
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [tools/db_stress] Error 1
make[1]: *** [tools/CMakeFiles/db_stress.dir/all] Error 2
[100%] Linking CXX executable db_bench
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -laio
collect2: error: ld returned 1 exit status
make[2]: *** [db_bench] Error 1
make[1]: *** [CMakeFiles/db_bench.dir/all] Error 2
make: *** [all] Error 2

**Comment by yapple** [comment]
gcc -v && g++ -v
gcc 版本在4.8.2 以上是可以遍过的

**Comment by shnuhw** [comment]
> gcc -v && g++ -v gcc 版本在4.8.2 以上是可以遍过的

版本问题好像解决了，aio链接不上我再看下，先谢谢大佬

**Comment by shnuhw** [comment]
安装成功了，谢谢大佬的指点！ @yapple
