### ISSUE TITLE
Curious question about compaction on dropped large CF tables e.g. > 100GB size.

### ISSUE THREAD

**Issue by hiqsociety** [bytedance/terarkdb#237]
If i delete / drop a Column Family, i know disk space is reclaimed immediately, so when compaction happens (how do i trigger compaction?), will read / write still possible concurrently with other CF tables not deleted?

CF 1 = 1TB
CF 2 = 1TB
CF 3 = 1TB etc

I havent implemented it yet so just curious what's the outcome of dropping a large CF in TB size, if the compaction will be very slow and choke the other operations on other CFs or not.

Can someone answer this? Thanks. Great work!

**Comment by noobpwnftw** [comment]
https://github.com/facebook/rocksdb/wiki/Column-Families

**Comment by hiqsociety** [comment]
thx
