### ISSUE TITLE
[BUG]Memtable test hangs

### ISSUE THREAD

**Issue by noobpwnftw** [bytedance/terarkdb#24]
[BUG]:
### Expected behavior
Test finish in reasonable time

### Actual behavior
Test hangs with larger `num_operations`

### Steps to reproduce the behavior
`memtablerep_bench -benchmarks seqreadwrite -num_threads 2 -num_operations=1000`

**Comment by royguo** [comment]
Thanks for reporting this bug.

@yapple and @ustcwelcome  Please have a look on this.

**Comment by yapple** [comment]
@noobpwnftw   good question. But that's not a bug.

**Comment by yapple** [comment]
![image](https://user-images.githubusercontent.com/10256548/103224473-afccf680-4962-11eb-8335-6773af06c3de.png)
![image](https://user-images.githubusercontent.com/10256548/103224483-b491aa80-4962-11eb-9ad1-0a5b37b46c86.png)
On my machine, Terarkdb's write rate is faster than RocksDB 5 times(29695:6047).

**Comment by noobpwnftw** [comment]
For concurrent tests, you need at least 2 threads(one thread is always writer in `memtablerep_bench`, if `-num_threads` is 1, `seqreadwrite` test is the same as `fillseq`.

**Comment by yapple** [comment]
> For concurrent tests, you need at least 2 threads(one thread is always writer in `memtablerep_bench`, if `-num_threads` is 1, `seqreadwrite` test is the same as `fillseq`.

Yes, we did the concurrent tests, and reproduce the hangs behavior. 
But what I meaning is that the bench logic leads to the behavior.
the faster the write rate, the more write data, the slower the bench rate.
because TerarkDB writes so fast, so on this bench, we hang.

**Comment by noobpwnftw** [comment]
If it is so fast, how long does it take to write and scan 1000 record 10 times(as per given command)?

**Comment by yapple** [comment]
1. The command's param num_operations means that scan all data num_operations times.
2. the fill thread finish until the read thread finish , you can see form that code
[ConcurrentFillBenchmarkThread](https://github.com/bytedance/terarkdb/blob/dev.1.3/memtable/memtablerep_bench.cc#L289-L295)
because the Skiplist is suppose multi version, so the amount of records will more more than 1000.
so, you can't use the benchmark to test the case like that write and scan 1000 record 10 times.

**Comment by yapple** [comment]
@noobpwnftw 
./memtablerep_bench -benchmarks fillrandom,readseq
maybe you need this command.

**Comment by noobpwnftw** [comment]
This issue can be fixed like this:
https://github.com/bytedance/terarkdb/pull/27/files#diff-927b97799f3309d24b770642c4e618d14177049a0fd16bdcc775c8e4d8cf3940L292-L294
