### ISSUE TITLE
long running db processes uses a lot of file descriptors

### ISSUE THREAD

**Issue by hiqsociety** [bytedance/terarkdb#240]
when i did 
lsof | wc -l
shows 300000+

i never close the db because it is always using it BUT how do i minimize using so many open files?

is this normal? i set uname -n 1024000 because of this.
mostly for fd is used in opened .sst

**Comment by yapple** [comment]
can you upload your OPTIONS file?

**Comment by hiqsociety** [comment]
it's ok now. no idea why. i've upgraded to use latest terarkdb
