### ISSUE TITLE
No Content in LOG file where using terarkdb in JNI

### ISSUE THREAD

**Issue by zhougit86** [bytedance/terarkdb#256]
### Expected behavior
expect to see debug infos in LOG

### Actual behavior

LOG size is 0

**Comment by yapple** [comment]
https://github.com/yapple/rocksdb-example/blob/dev_terark/src/main/java/org/example/RocksDBConnector.java

**Comment by yapple** [comment]
can you double check if there is a LOG using this demo, and replace the maven dependence of terakdb jni with yours

**Comment by zhougit86** [comment]
Thanks a lot, it turns out I used HEADER level, and no log is outputed. in debug level, a lot log is printed.

Furthermore, I want to understand what is the major reason terark get better performance than rocksdb? and How i can verify it in the log? it seems I didn't find the performance improve compared to rocksdb 5.17 in flink
