### ISSUE TITLE
Fix compile issues on MacOS

### ISSUE THREAD

**Issue by royguo** [bytedance/terarkdb#26]
### Expected behavior
TerarkDB should be built on MacOS without problem

### Actual behavior
Cannot be built due to some library missing problem

### Steps to reproduce the behavior
`./build.sh`

**Comment by jackwener** [comment]
@royguo Hi, Does this issue still exist?
I complie project still failed.

**Comment by skyzh** [comment]
> @royguo Hi, Does this issue still exist?
> I complie project still failed.

Would you please attach some detailed compile errors?

**Comment by jackwener** [comment]
> The following directory should be added to compiler include paths:
/terarkdb/third-party/terark-zip/3rdparty/boost-include
The following directory should be added to linker library paths:
/terarkdb/third-party/terark-zip/3rdparty/boost-include/stage/lib
[ 16%] Completed 'boost-project'
[ 16%] Built target boost-project
make: *** [all] Error 2

Here is log outputed  in the end.

**Comment by jackwener** [comment]
What's more, it maybe also occurred in the Linux.
I have found that it happened in the CI build.
@skyzh

**Comment by skyzh** [comment]
The failure happens long before the program exits.

```
/usr/bin/ld: zstdcli.o: in function `usage_advanced':
zstdcli.c:(.text+0x458): undefined reference to `ZSTD_maxCLevel'
/usr/bin/ld: zstdcli.o: in function `main':
zstdcli.c:(.text.startup+0x12d4): undefined reference to `ZSTD_maxCLevel'
/usr/bin/ld: ../lib/compress/zstdmt_compress.o: in function `ZSTDMT_compressChunk':
zstdmt_compress.c:(.text+0x3c): undefined reference to `ZSTD_compressBegin_usingCDict'
/usr/bin/ld: zstdmt_compress.c:(.text+0x79): undefined reference to `ZSTD_compressContinue'
/usr/bin/ld: zstdmt_compress.c:(.text+0xa1): undefined reference to `ZSTD_compressEnd'
/usr/bin/ld: zstdmt_compress.c:(.text+0xd6): undefined reference to `ZSTD_compressBegin_advanced'
/usr/bin/ld: zstdmt_compress.c:(.text+0x105): undefined reference to `ZSTD_compressContinue'
/usr/bin/ld: zstdmt_compress.c:(.text+0x136): undefined reference to `ZSTD_setCCtxParameter'
/usr/bin/ld: zstdmt_compress.c:(.text+0x154): undefined reference to `ZSTD_invalidateRepCodes'
```

Seems to be some linker errors.

**Comment by skyzh** [comment]
I just found out that you are creating a pull request on master branch in https://github.com/bytedance/terarkdb/pull/102. It turns out that our main branch is `dev.1.4`.

**Comment by orca-zhang** [comment]
I found the same problem and come from #163 .
