### ISSUE TITLE
About max subcompaction and blob size

### ISSUE THREAD

**Issue by zhougit86** [bytedance/terarkdb#262]
@yapple Master, I have 2 questions:
1, what's the reason terark set the max subcompaction to 1 even when the config is 0
2, what's the unit size of blob size? kb mb? and the size is counted after zstd/ snappy compression or before it?

**Comment by yapple** [comment]
1. subcompaction should be >= 1, it meaning a compaction  job will partition to how many sub compaction jobs
2. blob_size 's unit is byte, it meaning the threshold of value lenth to triiger kv separation

**Comment by zhougit86** [comment]
if subcompaction == 1, that means only one  "major" compaction will happen? no concurrent subcompaction?
