### ISSUE TITLE
supported platforms and compiler toolsets

### ISSUE THREAD

**Issue by Nireyflip** [bytedance/terarkdb#36]
hi, all, I wonder what's the basic supported compiler toolsets and platform to build terarkdb. I tried below environment and failed to build without any modification of build.sh.

Compiler: GCC 4.8.5, 4.9.0, 8.2.0
CentOS 7.2.x

but I build successfully as I disabled DWITH_TERARK_ZIP and DWITH_TOOLS. I can't find any reference about this by searching the wiki and [all-in-one-doc](https://bytedance.feishu.cn/docs/doccnZmYFqHBm06BbvYgjsHHcKc#cSFy9m). Is anyone to help with this issue?

**Comment by yapple** [comment]
can you add more error info?

**Comment by Nireyflip** [comment]
cmake version 3.6.2

**Comment by Nireyflip** [comment]
cmake version 3.6.2

**Comment by Nireyflip** [comment]
terarkdb branch version: dev1.3
cmake version 3.6.2
gcc (GCC) 8.2.0
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_TOOLS=ON     -DWITH_TERARK_ZIP=ON
compiling seems ok，problem arise as linking. Some logs are showed as below:
future.cpp:(.text._ZN5boost6fibers21future_error_categoryD0Ev[_ZN5boost6fibers21future_error_categoryD5Ev]+0xf): undefined reference to `std::_V2::error_category::~error_category()'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTIN5boost6fibers21future_error_categoryE[_ZTIN5boost6fibers21future_error_categoryE]+0x10): undefined reference to `typeinfo for std::_V2::error_category'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTVN5boost6fibers21future_error_categoryE[_ZTVN5boost6fibers21future_error_categoryE]+0x30): undefined reference to `std::_V2::error_category::_M_message(int) const'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTVN5boost6fibers21future_error_categoryE[_ZTVN5boost6fibers21future_error_categoryE]+0x40): undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const'

**Comment by Nireyflip** [comment]
I compiled the source code via recommand method 1.
cmake version 3.6.2
gcc (GCC) 8.2.0
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_TOOLS=ON     -DWITH_TERARK_ZIP=ON
compiling seems ok，problem arise as linking. Some logs are showed as below:

future.cpp:(.text._ZN5boost6fibers21future_error_categoryD0Ev[_ZN5boost6fibers21future_error_categoryD5Ev]+0xf): undefined reference to `std::_V2::error_category::~error_category()'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTIN5boost6fibers21future_error_categoryE[_ZTIN5boost6fibers21future_error_categoryE]+0x10): undefined reference to `typeinfo for std::_V2::error_category'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTVN5boost6fibers21future_error_categoryE[_ZTVN5boost6fibers21future_error_categoryE]+0x30): undefined reference to `std::_V2::error_category::_M_message(int) const'
/usr/bin/ld: ../../third-party/terark-zip/3rdparty/boost-include/stage/lib/libboost_fiber.a(future.o):(.data.rel.ro._ZTVN5boost6fibers21future_error_categoryE[_ZTVN5boost6fibers21future_error_categoryE]+0x40): undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const'

**Comment by Nireyflip** [comment]
I resolved this by upgrading cmake and gcc, thx
