### ISSUE TITLE
TerarkFS env support

### ISSUE THREAD

**Issue by royguo** [bytedance/terarkdb#7]
[Enhancement]:
### Problem
- Filesystems(e.g. ext4) are built for general purpose which is not optimized for append-only & LSM storage systems
- SPDK driver and multi-layer storage (e.g. NVMe SSD + Optane SSD + Optane Memory) should be used for better performance

### Solution
@levisonchen Please add a short description on how we gona implement this feature

### Release
- v1.4

**Comment by skyzh** [comment]
It seems that we have already gained ZenFS support (though not TerarkFS). Shall we close this issue for now? cc @royguo @levisonchen
