### ISSUE TITLE
how can we test terarkfs?

### ISSUE THREAD

**Issue by hiqsociety** [bytedance/terarkdb#92]
how can we test terarkfs?

**Comment by skyzh** [comment]
Hi, could you elaborate more details on this? e.g. what problem do you need, which branch are you using.

**Comment by hiqsociety** [comment]
oh hi, there are people actually responding to issues here. just curious, how do you implement mysql with terarkdb storage engine first?

**Comment by skyzh** [comment]
Thanks for your interest!

As far as I know, TerarkDB is simply a key-value storage engine. Things like "implement MySQL with TerarkDB storage engine" and "TerarkFS" does not relate to the TerarkDB project itself. You may join our Slack (see readme) for discussion like this.
