### ISSUE TITLE
There are some exmaple for golang to call cgo by Terarkdb ?

### ISSUE THREAD

**Issue by enefuture** [bytedance/terarkdb#98]
Hi 
    I want to use terarkdb by golang, like https://github.com/tecbot/gorocksdb. Can you give some example from this?

**Comment by skyzh** [comment]
Using TerarkDB with golang is not officially supported. Generally speaking, TerarkDB is compatible with RocksDB 5.x. You may use any go binding which supports RocksDB 5.x and replace the binary with TerarkDB.

**Comment by enefuture** [comment]
I build a version , has an error:

CGO_CFLAGS="-I/data/homework/terarkdb/output/include" CGO_LDFLAGS="-L/data/homework/terarkdb/output/lib -L/data/homework/terarkdb/output -L/usr/lib64 -lterarkdb -lterark-zip-r -lbz2 -ljemalloc -llz4 -lsnappy -lz -lzstd -pthread -lgomp -lrt -ldl -laio" go build -o bin/terark-example main.go

#github.com/enefuture/gorocksdb
/data/homework/terarkdb/output/lib/libterarkdb.a(db_impl.cc.o): In function `__tls_init':
/data/homework/terarkdb/db/db_impl.cc:1634: undefined reference to `boost::fibers::context::active_pp()'
/data/homework/terarkdb/third-party/terark-zip/3rdparty/boost-include/boost/fiber/buffered_channel.hpp:124: undefined reference to `boost::fibers::context::active()'
/data/homework/terarkdb/third-party/terark-zip/3rdparty/boost-include/boost/fiber/buffered_channel.hpp:147: undefined reference to `boost::fibers::context::schedule(boost::fibers::context*)'
/data/homework/terarkdb/output/lib/libterarkdb.a(db_impl.cc.o): In function `boost::context::fiber boost::context::fiber::resume_with<boost::fibers::context::resume(boost::fibers::context**)::{lambda(boost::context::fiber&&)#1}>(boost::fibers::context::resume(boost::fibers::context**)::{lambda(boost::context::fiber&&)#1}&&) &&':
/data/homework/terarkdb/third-party/terark-zip/3rdparty/boost-include/boost/context/fiber_fcontext.hpp:295: undefined reference to `ontop_fcontext'

how to fix this problem？

**Comment by skyzh** [comment]
You should link required libraries for TerarkDB. In this case, the boost library.

**Comment by enefuture** [comment]
there are some recommed boost version ? i build a boost.1.76.0, but not work

**Comment by skyzh** [comment]
> there are some recommed boost version ? i build a boost.1.76.0, but not work

We have a vendered version in `third-party` directory.

**Comment by skyzh** [comment]
> > there are some recommed boost version ? i build a boost.1.76.0, but not work
> 
> We have a vendered version in `third-party` directory.

To be exact, this is vendered by TerarkZipTable. You may also disable TerarkZipTable support to avoid using boost.

**Comment by enefuture** [comment]
> > > there are some recommed boost version ? i build a boost.1.76.0, but not work
> > 
> > 
> > We have a vendered version in `third-party` directory.
> 
> To be exact, this is vendered by TerarkZipTable. You may also disable TerarkZipTable support to avoid using boost.

I want to use TerarkZipTable, but i found TerarkZipTable not support golang to call cgo. eg:
rocksdb::NewTerarkZipTableFactory()
rocksdb::TerarkZipTableOptions()

Could you support this feature in the future ?

**Comment by skyzh** [comment]
This seems to be an issue with gorocksdb side, instead of ours. Currently, we have no plan to maintain a golang binding of TerarkDB. If you are interested in this, you may modify gorocksdb yourself.
